apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cli
  description: |
    Lux-CLI is a command-line interface for building, deploying, and maintaining Lux
    Subnets. It can be used to support the entire Subnet development lifecycle from initial
    prototyping to production deployments. Lux-CLI is available for Linux and Mac, and is open
    source on GitHub.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: luxdefi/cli
spec:
  type: service
  owner: platform-tooling
  lifecycle: production
  system: platform
  dependsOn:
    - component:node
    - component:netrunner
    - resource:posthog
    - component:subnet-evm
    - component:coreth
    - component:lpm
