site_name: cli
site_description: Lux-CLI is a command-line interface for building, deploying, and maintaining Lux Subnets. It can be used to support the entire Subnet development lifecycle from initial prototyping to production deployments. Lux-CLI is available for Linux and Mac, and is open source on GitHub.
nav:
  - Introduction: index.md
  - Ledger Simulator: ledger-simulator.md
plugins:
  - techdocs-core
